tap "beeftornado/rmtree"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "bat"
brew "deno"
brew "exa"
brew "fd"
brew "fzy"
brew "ghq"
brew "git"
brew "git-delta"
brew "go"
brew "gopls"
brew "hugo"
brew "mas"
brew "neovim"
brew "ripgrep"
brew "sd"
brew "tig"
brew "zsh"
cask "alfred"
cask "discord"
cask "docker"
cask "font-hackgen-nerd"
cask "forklift"
cask "google-chrome"
cask "karabiner-elements"
cask "visual-studio-code"
cask "vlc"
cask "wezterm"
mas "1Password 7", id: 1333542190
mas "Magnet", id: 441258766
mas "Microsoft Remote Desktop", id: 1295203466
mas "Tailscale", id: 1475387142
mas "The Unarchiver", id: 425424353
mas "Twitter", id: 1482454543
